// function extractBestPhrase(text: string, maxPhraseLength: number = 4): string {
//   // Normalize text: Remove special characters except spaces and split into words
//   const words = text
//     .toLowerCase()
//     .replace(/[^a-zA-Z0-9' ]+/g, "") // Remove punctuation
//     .split(/\s+/) // Split by spaces
//     .filter((word) => word.length > 0); // Remove empty entries

//   const phraseFrequency = new Map<string, number>();

//   // Extract phrases of length 1 to maxPhraseLength and count occurrences
//   for (let i = 0; i < words.length; i++) {
//     for (let length = 1; length <= maxPhraseLength; length++) {
//       if (i + length <= words.length) {
//         const phrase = words.slice(i, i + length).join(" ");
//         phraseFrequency.set(phrase, (phraseFrequency.get(phrase) || 0) + 1);
//       }
//     }
//   }

//   // Find the most relevant phrase (longest, most frequent)
//   let bestPhrase = "";
//   let maxScore = 0;

//   phraseFrequency.forEach((count, phrase) => {
//     const score = phrase.split(" ").length * count; // Prioritize longer frequent phrases
//     if (score > maxScore) {
//       maxScore = score;
//       bestPhrase = phrase;
//     }
//   });

//   return bestPhrase;
// }

// // Example usage:
// const inputText =
//   "There will never have been a transformation of a Country like the transformation that is happening, for all to see, in the United States of America. Companies are pouring into our Country at levels never seen before, with Jobs (and Money!) to follow. It is a beautiful thing to";
// const bestPhrase = extractBestPhrase(inputText);
// console.log(bestPhrase);


// import natural from 'natural';

// const tokenizer = new natural.WordTokenizer();
// // const stopWords = new Set([
// //     "the", "there", "nothing", "will", "never", "of", "a", "is", "to", "in", "for", "that", "with", "on", "at", "it", "as", "be", "this", "by", "will", "are", "an", "and", "have", "been"
// // ]);
// const stopWords = new Set([
//   // **Articles**
//   "a",
//   "an",
//   "the",

//   // **Pronouns**
//   "i",
//   "me",
//   "my",
//   "myself",
//   "we",
//   "our",
//   "ours",
//   "ourselves",
//   "you",
//   "your",
//   "yours",
//   "yourself",
//   "yourselves",
//   "he",
//   "him",
//   "his",
//   "himself",
//   "she",
//   "her",
//   "hers",
//   "herself",
//   "it",
//   "its",
//   "itself",
//   "they",
//   "them",
//   "their",
//   "theirs",
//   "themselves",

//   // **Prepositions**
//   "about",
//   "above",
//   "after",
//   "against",
//   "along",
//   "among",
//   "around",
//   "as",
//   "at",
//   "before",
//   "behind",
//   "below",
//   "beneath",
//   "beside",
//   "between",
//   "beyond",
//   "but",
//   "by",
//   "down",
//   "during",
//   "except",
//   "for",
//   "from",
//   "in",
//   "inside",
//   "into",
//   "like",
//   "near",
//   "of",
//   "off",
//   "on",
//   "onto",
//   "out",
//   "outside",
//   "over",
//   "past",
//   "since",
//   "through",
//   "throughout",
//   "to",
//   "toward",
//   "under",
//   "until",
//   "up",
//   "upon",
//   "with",
//   "within",
//   "without",

//   // **Conjunctions**
//   "and",
//   "but",
//   "or",
//   "nor",
//   "so",
//   "yet",
//   "although",
//   "because",
//   "if",
//   "once",
//   "since",
//   "though",
//   "unless",
//   "until",
//   "when",
//   "where",
//   "while",
//   "whether",

//   // **Helping Verbs (Auxiliary Verbs)**
//   "am",
//   "is",
//   "are",
//   "was",
//   "were",
//   "be",
//   "been",
//   "being",
//   "can",
//   "could",
//   "do",
//   "does",
//   "did",
//   "doing",
//   "has",
//   "have",
//   "had",
//   "having",
//   "shall",
//   "should",
//   "will",
//   "would",
//   "may",
//   "might",
//   "must",
//   "ought",

//   // **Common Adverbs**
//   "again",
//   "almost",
//   "already",
//   "also",
//   "although",
//   "always",
//   "anyway",
//   "anywhere",
//   "back",
//   "before",
//   "besides",
//   "certainly",
//   "definitely",
//   "down",
//   "ever",
//   "everywhere",
//   "exactly",
//   "far",
//   "forever",
//   "forth",
//   "further",
//   "hence",
//   "here",
//   "however",
//   "just",
//   "least",
//   "less",
//   "maybe",
//   "more",
//   "most",
//   "much",
//   "nearly",
//   "never",
//   "nevertheless",
//   "now",
//   "nowhere",
//   "often",
//   "once",
//   "only",
//   "perhaps",
//   "probably",
//   "quite",
//   "rather",
//   "really",
//   "right",
//   "seldom",
//   "simply",
//   "so",
//   "sometimes",
//   "soon",
//   "still",
//   "then",
//   "there",
//   "therefore",
//   "though",
//   "thus",
//   "today",
//   "together",
//   "too",
//   "totally",
//   "truly",
//   "twice",
//   "under",
//   "usually",
//   "very",
//   "well",
//   "where",
//   "whereas",
//   "wherever",
//   "whether",
//   "why",
//   "yet",

//   // **Common Verbs**
//   "go",
//   "come",
//   "do",
//   "did",
//   "done",
//   "does",
//   "going",
//   "got",
//   "gets",
//   "getting",
//   "give",
//   "given",
//   "giving",
//   "keep",
//   "kept",
//   "let",
//   "lets",
//   "made",
//   "make",
//   "makes",
//   "making",
//   "put",
//   "puts",
//   "putting",
//   "say",
//   "said",
//   "says",
//   "see",
//   "sees",
//   "seeing",
//   "seen",
//   "take",
//   "takes",
//   "taken",
//   "taking",
//   "tell",
//   "tells",
//   "telling",
//   "think",
//   "thinks",
//   "thinking",
//   "thought",
//   "want",
//   "wants",
//   "wanting",
//   "went",

//   // **Common Interjections**
//   "ah",
//   "aha",
//   "alas",
//   "dear",
//   "eh",
//   "er",
//   "hmm",
//   "oh",
//   "oops",
//   "ouch",
//   "uh",
//   "uhh",
//   "uh-oh",
//   "um",
//   "umm",
//   "whoa",
//   "wow",
//   "yay",
//   "yeah",
//   "yep",
//   "yikes",
//   "yo",
//   "nothing",
//   "ve",
//   "prepared",
// ]);


// function extractMemeWord(text: string): string {
//     const words = tokenizer.tokenize(text.toLowerCase());
    
//     // Remove stop words
//     const filteredWords = words.filter(word => !stopWords.has(word));

//     // Count word frequency
//     const frequency = new Map<string, number>();
//     for (const word of filteredWords) {
//         frequency.set(word, (frequency.get(word) || 0) + 1);
//     }

//     // Find the most meaningful & frequent word
//     let bestWord = '';
//     let maxCount = 0;

//     for (const [word, count] of frequency) {
//         if (count > maxCount) {
//             bestWord = word;
//             maxCount = count;
//         }
//     }

//     return bestWord;
// }

// // **Example Usage**
// const tweet =
//   "Nothing could’ve prepared me for her morning routine (don’t check replies) 😭";
// console.log(extractMemeWord(tweet));  // ✅ Expected: "transformation"

import natural from 'natural';

const tokenizer = new natural.WordTokenizer();

const stopWords = new Set([
  "relentlessly",
  "breaking",
  "a",
  "an",
  "the",
  "i",
  "me",
  "my",
  "myself",
  "we",
  "our",
  "ours",
  "ourselves",
  "you",
  "your",
  "yours",
  "yourself",
  "yourselves",
  "he",
  "him",
  "his",
  "himself",
  "she",
  "her",
  "hers",
  "herself",
  "it",
  "its",
  "itself",
  "they",
  "them",
  "their",
  "theirs",
  "themselves",
  "about",
  "above",
  "after",
  "against",
  "along",
  "among",
  "around",
  "as",
  "at",
  "before",
  "behind",
  "below",
  "beneath",
  "beside",
  "between",
  "beyond",
  "but",
  "by",
  "down",
  "during",
  "except",
  "for",
  "from",
  "in",
  "inside",
  "into",
  "like",
  "near",
  "of",
  "off",
  "on",
  "onto",
  "out",
  "outside",
  "over",
  "past",
  "since",
  "through",
  "throughout",
  "to",
  "toward",
  "under",
  "until",
  "up",
  "upon",
  "with",
  "within",
  "without",
  "and",
  "but",
  "or",
  "nor",
  "so",
  "yet",
  "although",
  "because",
  "if",
  "once",
  "since",
  "though",
  "unless",
  "until",
  "when",
  "where",
  "while",
  "whether",
  "am",
  "is",
  "are",
  "was",
  "were",
  "be",
  "been",
  "being",
  "can",
  "could",
  "do",
  "does",
  "did",
  "doing",
  "has",
  "have",
  "had",
  "having",
  "shall",
  "should",
  "will",
  "would",
  "may",
  "might",
  "must",
  "ought",
  "again",
  "almost",
  "already",
  "also",
  "although",
  "always",
  "anyway",
  "anywhere",
  "back",
  "before",
  "besides",
  "certainly",
  "definitely",
  "down",
  "ever",
  "everywhere",
  "exactly",
  "far",
  "forever",
  "forth",
  "further",
  "hence",
  "here",
  "however",
  "just",
  "least",
  "less",
  "maybe",
  "more",
  "most",
  "much",
  "nearly",
  "never",
  "nevertheless",
  "now",
  "nowhere",
  "often",
  "once",
  "only",
  "perhaps",
  "probably",
  "quite",
  "rather",
  "really",
  "right",
  "seldom",
  "simply",
  "so",
  "sometimes",
  "soon",
  "still",
  "then",
  "there",
  "therefore",
  "though",
  "thus",
  "today",
  "together",
  "too",
  "totally",
  "truly",
  "twice",
  "under",
  "usually",
  "very",
  "well",
  "where",
  "whereas",
  "wherever",
  "whether",
  "why",
  "yet",
  "go",
  "come",
  "do",
  "did",
  "done",
  "does",
  "going",
  "got",
  "gets",
  "getting",
  "give",
  "given",
  "giving",
  "keep",
  "kept",
  "let",
  "lets",
  "made",
  "make",
  "makes",
  "making",
  "put",
  "puts",
  "putting",
  "say",
  "said",
  "says",
  "see",
  "sees",
  "seeing",
  "seen",
  "take",
  "takes",
  "taken",
  "taking",
  "tell",
  "tells",
  "telling",
  "think",
  "thinks",
  "thinking",
  "thought",
  "want",
  "wants",
  "wanting",
  "went",
  "ah",
  "aha",
  "alas",
  "dear",
  "eh",
  "er",
  "hmm",
  "oh",
  "oops",
  "ouch",
  "insanely",
  "uh",
  "uhh",
  "uh-oh",
  "um",
  "umm",
  "whoa",
  "wow",
  "wishing",
  "celebrating",
  "blessed",
  "yay",
  "yeah",
  "yep",
  "yikes",
  "everyone",
  "yo",
  "nothing",
  "sure",
  "ve",
  "prepared",
  "that",
  "a",
  "able",
  "about",
  "above",
  "abst",
  "accordance",
  "according",
  "accordingly",
  "across",
  "act",
  "actually",
  "added",
  "adj",
  "affected",
  "affecting",
  "affects",
  "after",
  "afterwards",
  "again",
  "against",
  "ah",
  "all",
  "almost",
  "alone",
  "along",
  "already",
  "also",
  "although",
  "always",
  "am",
  "among",
  "amongst",
  "an",
  "and",
  "announce",
  "another",
  "any",
  "anybody",
  "anyhow",
  "anymore",
  "anyone",
  "anything",
  "anyway",
  "anyways",
  "anywhere",
  "apparently",
  "approximately",
  "are",
  "aren",
  "arent",
  "arise",
  "around",
  "as",
  "aside",
  "ask",
  "asking",
  "at",
  "auth",
  "available",
  "away",
  "awfully",
  "b",
  "back",
  "be",
  "became",
  "because",
  "become",
  "becomes",
  "becoming",
  "been",
  "before",
  "beforehand",
  "begin",
  "beginning",
  "beginnings",
  "begins",
  "behind",
  "being",
  "believe",
  "below",
  "beside",
  "besides",
  "between",
  "beyond",
  "biol",
  "both",
  "brief",
  "briefly",
  "but",
  "by",
  "c",
  "ca",
  "came",
  "can",
  "cannot",
  "can't",
  "cause",
  "causes",
  "certain",
  "certainly",
  "co",
  "com",
  "come",
  "comes",
  "contain",
  "containing",
  "contains",
  "could",
  "couldnt",
  "d",
  "date",
  "did",
  "didn't",
  "different",
  "do",
  "does",
  "doesn't",
  "doing",
  "done",
  "don't",
  "down",
  "downwards",
  "due",
  "during",
  "e",
  "each",
  "ed",
  "edu",
  "effect",
  "eg",
  "eight",
  "eighty",
  "either",
  "else",
  "elsewhere",
  "end",
  "ending",
  "enough",
  "especially",
  "et",
  "et-al",
  "etc",
  "even",
  "ever",
  "every",
  "everybody",
  "everyone",
  "everything",
  "everywhere",
  "ex",
  "except",
  "f",
  "far",
  "few",
  "ff",
  "fifth",
  "first",
  "five",
  "fix",
  "followed",
  "following",
  "follows",
  "for",
  "former",
  "formerly",
  "forth",
  "found",
  "four",
  "from",
  "further",
  "furthermore",
  "g",
  "gave",
  "get",
  "gets",
  "getting",
  "give",
  "given",
  "gives",
  "giving",
  "go",
  "goes",
  "gone",
  "got",
  "gotten",
  "h",
  "had",
  "happens",
  "hardly",
  "has",
  "hasn't",
  "have",
  "haven't",
  "having",
  "he",
  "hed",
  "hence",
  "her",
  "here",
  "hereafter",
  "hereby",
  "herein",
  "heres",
  "hereupon",
  "hers",
  "herself",
  "hes",
  "hi",
  "hid",
  "him",
  "himself",
  "his",
  "hither",
  "home",
  "how",
  "howbeit",
  "however",
  "hundred",
  "i",
  "id",
  "ie",
  "if",
  "i'll",
  "im",
  "immediate",
  "immediately",
  "importance",
  "important",
  "in",
  "inc",
  "indeed",
  "index",
  "information",
  "instead",
  "into",
  "invention",
  "inward",
  "is",
  "isn't",
  "it",
  "itd",
  "it'll",
  "its",
  "itself",
  "i've",
  "j",
  "just",
  "k",
  "keep",
  "keeps",
  "kept",
  "kg",
  "km",
  "know",
  "known",
  "knows",
  "l",
  "largely",
  "last",
  "lately",
  "later",
  "latter",
  "latterly",
  "least",
  "less",
  "lest",
  "let",
  "lets",
  "like",
  "liked",
  "likely",
  "line",
  "little",
  "'ll",
  "look",
  "looking",
  "looks",
  "ltd",
  "m",
  "made",
  "mainly",
  "make",
  "makes",
  "many",
  "may",
  "maybe",
  "me",
  "mean",
  "means",
  "meantime",
  "meanwhile",
  "merely",
  "mg",
  "might",
  "million",
  "miss",
  "ml",
  "more",
  "moreover",
  "most",
  "mostly",
  "mr",
  "mrs",
  "much",
  "mug",
  "must",
  "my",
  "myself",
  "n",
  "na",
  "name",
  "namely",
  "nay",
  "nd",
  "near",
  "nearly",
  "necessarily",
  "necessary",
  "need",
  "needs",
  "neither",
  "never",
  "nevertheless",
  "new",
  "next",
  "nine",
  "ninety",
  "no",
  "nobody",
  "non",
  "none",
  "nonetheless",
  "noone",
  "nor",
  "normally",
  "nos",
  "not",
  "noted",
  "nothing",
  "now",
  "nowhere",
  "o",
  "obtain",
  "obtained",
  "obviously",
  "of",
  "off",
  "often",
  "oh",
  "ok",
  "okay",
  "old",
  "omitted",
  "on",
  "once",
  "one",
  "ones",
  "only",
  "onto",
  "or",
  "ord",
  "other",
  "others",
  "otherwise",
  "ought",
  "our",
  "ours",
  "ourselves",
  "out",
  "outside",
  "over",
  "overall",
  "owing",
  "own",
  "p",
  "page",
  "pages",
  "part",
  "particular",
  "particularly",
  "past",
  "per",
  "perhaps",
  "placed",
  "please",
  "plus",
  "poorly",
  "possible",
  "possibly",
  "potentially",
  "pp",
  "predominantly",
  "present",
  "previously",
  "primarily",
  "probably",
  "promptly",
  "proud",
  "provides",
  "put",
  "q",
  "que",
  "quickly",
  "quite",
  "qv",
  "r",
  "ran",
  "rather",
  "rd",
  "re",
  "readily",
  "really",
  "recent",
  "recently",
  "ref",
  "refs",
  "regarding",
  "regardless",
  "regards",
  "related",
  "relatively",
  "research",
  "respectively",
  "resulted",
  "resulting",
  "results",
  "right",
  "run",
  "s",
  "said",
  "same",
  "saw",
  "say",
  "saying",
  "says",
  "sec",
  "section",
  "see",
  "seeing",
  "seem",
  "seemed",
  "seeming",
  "seems",
  "seen",
  "self",
  "selves",
  "sent",
  "seven",
  "several",
  "shall",
  "she",
  "shed",
  "she'll",
  "shes",
  "should",
  "shouldn't",
  "show",
  "showed",
  "shown",
  "showns",
  "shows",
  "significant",
  "significantly",
  "similar",
  "similarly",
  "since",
  "six",
  "slightly",
  "so",
  "some",
  "somebody",
  "somehow",
  "someone",
  "somethan",
  "something",
  "sometime",
  "sometimes",
  "somewhat",
  "somewhere",
  "soon",
  "sorry",
  "specifically",
  "specified",
  "specify",
  "specifying",
  "still",
  "stop",
  "strongly",
  "sub",
  "substantially",
  "successfully",
  "such",
  "sufficiently",
  "suggest",
  "sup",
  "sure",
  "t",
  "take",
  "taken",
  "taking",
  "tell",
  "tends",
  "th",
  "than",
  "thank",
  "thanks",
  "thanx",
  "that",
  "that'll",
  "thats",
  "that've",
  "the",
  "their",
  "theirs",
  "them",
  "themselves",
  "then",
  "thence",
  "there",
  "thereafter",
  "thereby",
  "thered",
  "therefore",
  "therein",
  "there'll",
  "thereof",
  "therere",
  "theres",
  "thereto",
  "thereupon",
  "there've",
  "these",
  "they",
  "theyd",
  "they'll",
  "theyre",
  "they've",
  "think",
  "this",
  "those",
  "thou",
  "though",
  "thoughh",
  "thousand",
  "throug",
  "through",
  "throughout",
  "thru",
  "thus",
  "til",
  "tip",
  "to",
  "together",
  "too",
  "took",
  "toward",
  "towards",
  "tried",
  "tries",
  "truly",
  "try",
  "trying",
  "ts",
  "twice",
  "two",
  "u",
  "un",
  "under",
  "unfortunately",
  "unless",
  "unlike",
  "unlikely",
  "until",
  "unto",
  "up",
  "upon",
  "ups",
  "us",
  "use",
  "used",
  "useful",
  "usefully",
  "usefulness",
  "uses",
  "using",
  "usually",
  "v",
  "value",
  "various",
  "'ve",
  "very",
  "via",
  "viz",
  "vol",
  "vols",
  "vs",
  "w",
  "want",
  "wants",
  "was",
  "wasn't",
  "way",
  "we",
  "wed",
  "welcome",
  "we'll",
  "went",
  "were",
  "weren't",
  "we've",
  "what",
  "whatever",
  "what'll",
  "whats",
  "when",
  "whence",
  "whenever",
  "where",
  "whereafter",
  "whereas",
  "whereby",
  "wherein",
  "wheres",
  "whereupon",
  "wherever",
  "whether",
  "which",
  "while",
  "whim",
  "whither",
  "who",
  "whod",
  "whoever",
  "whole",
  "who'll",
  "whom",
  "whomever",
  "whos",
  "whose",
  "why",
  "widely",
  "willing",
  "wish",
  "with",
  "within",
  "without",
  "won't",
  "words",
  "world",
  "would",
  "wouldn't",
  "www",
  "x",
  "y",
  "yes",
  "yet",
  "you",
  "youd",
  "you'll",
  "your",
  "youre",
  "yours",
  "yourself",
  "yourselves",
  "you've",
  "z",
  "zero",
]);

// Helper function to check if a word is a meaningful word (noun-like)
const isMeaningfulWord = (word: string) => {
  // For simplicity, assume words longer than 2 characters are meaningful
  return word.length > 2;
};

function extractMemeWord(text: string): string {
    const words = tokenizer.tokenize(text.toLowerCase());

    // Remove stop words and filter meaningful words
    const filteredWords = words.filter(word => !stopWords.has(word) && isMeaningfulWord(word));

    // Combine adjacent words (simple heuristic for multi-word phrases)
    let phrases = [];
    for (let i = 0; i < filteredWords.length - 1; i++) {
        const combinedPhrase = filteredWords[i] + ' ' + filteredWords[i + 1];
        phrases.push(combinedPhrase);
    }

    // Count frequency of these noun phrases
    const frequency = new Map<string, number>();
    for (const phrase of phrases) {
        frequency.set(phrase, (frequency.get(phrase) || 0) + 1);
    }

    // Find the most frequent noun phrase
    let bestPhrase = '';
    let maxCount = 0;
    for (const [phrase, count] of frequency) {
        if (count > maxCount) {
            bestPhrase = phrase;
            maxCount = count;
        }
    }

    return bestPhrase;
}

// **Example Usage**
const tweet =
  "CONFIRMED - DOGE SAYS USAID GAVE CHELSEA CLINTON $84 MILLION - WHICH WAS 'SUPPOSED' TO GO FOR RELIEF IN HAITI - LINE ITEMS SHOW 3 MILLION, OF THE $84 MILLION, WAS SPENT ON CHELSEA CLINTONS WEDDING AND.";
console.log(extractMemeWord(tweet));  // ✅ Expected: "morning routine"

const s = extractMemeWord(tweet);
// console.log(s)

// const url =
//   `https://api.coingecko.com/api/v3/search?query=${s}`;
// const options = {
//   method: "GET",
//   headers: {
//     accept: "application/json",
//     "x_cg_demo_api_key": "CG-SoW3z999JKiSEEq2qmhHYAsm",
//   },
// };

// fetch(url, options)
//   .then((res) => res.json())
//   .then((json) => console.log(json))
//   .catch((err) => console.error(err));

import nlp from "compromise";
import { stopWordDatasets } from './trainingDatasets';

// Function to extract and filter nouns from text
// function extractNouns(text: string): string[] {
//   // Parse the text with compromise
//   const doc = nlp(text);

//   // Extract all nouns (both single words and multi-word phrases)
//   const nouns = doc.nouns().out("array");
//   console.log(nouns)

//   // Filter out non-nouns (pronouns, verbs, adjectives, etc.)
//   const validNouns = nouns.filter((noun: string) => {
//     console.log(noun)
//     const isPronoun = [
//       "they",
//       "he",
//       "she",
//       "it",
//       "me",
//       "you",
//       "us",
//       "we",
//       "him",
//       "her",
//       "the",
//       "first",
//     ].includes(noun);
//     console.log(isPronoun)
//     return !isPronoun && noun.length > 1; // Ignore single-character words and pronouns
//   });

//   return validNouns;
// }

function extractNouns(text: string): string[] {
  // Parse the text with compromise
  const doc = nlp(text);

  // Extract all nouns (both single words and multi-word phrases)
  const nouns = doc.nouns().out("array");

  // List of words to remove
  const isPronoun: any = stopWordDatasets;

  // Filter out non-nouns and remove unwanted words from multi-word phrases
  const validNouns = nouns
    .map((noun: string) => {
      // Remove words from `isPronoun` in the noun string
      const cleanedNoun = noun
        .split(" ") // Split multi-word phrases
        .filter((word) => !isPronoun.includes(word.toLowerCase())) // Remove unwanted words
        .join(" ") // Rejoin remaining words
        .trim(); // Remove extra spaces

      console.log("Cleaned noun:", cleanedNoun);
      return cleanedNoun;
    })
    .filter((noun:any) => noun.length > 1); // Ignore empty results

  return validNouns;
}


// // Function to get the most unique noun(s) and handle multi-word phrases
// function getMostUniqueNouns(text: string): string[] {
//   const nouns = extractNouns(text);

//   // To identify the "most unique" noun(s), we'll split multi-word phrases and count their frequency
//   const nounFrequency: { [key: string]: number } = {};

//   // Split multi-word phrases and count individual nouns
//   nouns.forEach((noun: string) => {
//     // Split multi-word phrases into individual words if needed
//     const splitNouns = noun.split(" ");
//     splitNouns.forEach((word) => {
//       nounFrequency[word] = (nounFrequency[word] || 0) + 1;
//     });
//   });

//   // Sort nouns by frequency and return the least frequent ones as the most unique
//   const sortedNouns = Object.keys(nounFrequency).sort(
//     (a, b) => nounFrequency[a] - nounFrequency[b]
//   );

//   // Return the most unique noun(s)
//   return sortedNouns;
// }

// // Example usage
// const text =
//   "Congratulations to Judge Susan Crawford on her victory, and to the people of Wisconsin for electing a judge who believes in the rule of law and protecting our freedoms.";

// const uniqueNouns = getMostUniqueNouns(text);
// console.log("Most Unique Nouns:", uniqueNouns);

function getMostUniqueNouns(text: any) {
  const nouns = extractNouns(text);

  // Object to store the frequency of each noun
  const nounFrequency: any = {};

  // Count occurrences of each noun
  nouns.forEach((noun) => {
    const words = noun.split(" "); // Split multi-word phrases
    words.forEach((word) => {
      nounFrequency[word] = (nounFrequency[word] || 0) + 1;
    });
  });

  // Sort nouns by frequency (ascending for uniqueness)
  const sortedNouns = Object.keys(nounFrequency).sort(
    (a, b) => nounFrequency[a] - nounFrequency[b]
  );

  // Return the two least frequent (most unique) nouns
  return sortedNouns.slice(0, 3);
}

// Example usage
const text =
  "Obituary for my father. Richard Warner Carlson died at 84 on March 24, 2025 at home in Boca Grande, Florida after six weeks of illness. He refused all painkillers to the end and left this world with dignity and clarity, holding the hands of his children with his dogs at his";

const uniqueNouns = getMostUniqueNouns(text);
console.log("Most Unique Nouns:", uniqueNouns);

export {getMostUniqueNouns}